- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.config/:
      glob: true
      path: config/*
    ~/.zplug:
    ~/.zshenv:
    ~/.ssh/config: ssh/config
