- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.config/:
      glob: true
      path: config/*
    ~/.zplug:
    ~/.zshenv:
    ~/.ssh/config: ssh/config
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.default-python-packages: default-python-packages
