#!/usr/bin/env bash

DARKGRAY='\033[1;30m'
RED='\033[0;31m'
LIGHTRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
LIGHTPURPLE='\033[1;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
SET='\033[0m'

set -e

# make sure submodules are initalized
git submodule update --init --recursive

########
# BREW #
########
if ! [ -x "$(command -v brew)" ]; then
  echo -e "${PURPLE}Installing homebrew...${SET}"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo -e "${DARKGRAY}Homebrew already installed, skipping...${SET}"
fi

echo -ne "${PURPLE}Install packages from Brewfile${SET} (${GREEN}y${SET}/${RED}N${SET}) => "; read answer
if [[ $answer == "y" ]] || [[ $answer == "Y" ]] ; then
  brew bundle
else
  echo -e "${DARKGRAY}Skipping Brewfile...${SET}"
fi

############
# DOTFILES #
############

echo -e "${PURPLE}Installing dotfiles...${SET}"

CONFIG=".install.conf.yaml"
DOTBOT_DIR=".dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
